site_name: prettymaps
site_url: https://marceloprates.github.io/prettymaps/
docs_dir: docs
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Usage: usage.md
  - API Reference: api.md
theme:
  name: material
  palette:
    primary: indigo
    accent: pink
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
            docstring_style: google
